name = "bi-connector"
title = "MongoDB Connector for BI"

intersphinx = ["https://docs.mongodb.com/manual/objects.inv", "https://docs.atlas.mongodb.com/objects.inv"]

toc_landing_pages = ["/installation", "/client-applications", "/authentication", "/schema-configuration", "/components", "/reference", "/release-notes"]

[substitutions]
branch = "``{0}``'.format(conf.git.branches.current)"
copy = "&trade;"
year = "{0}'.format(datetime.date.today().year)"
ent-build = "MongoDB Enterprise"
hardlink = "https://docs.mongodb.com/bi-connector/"
bi = "MongoDB Connector for BI"
bi-short = "BI Connector"
bi-atlas = "MongoDB Connector for Business Intelligence for MongoDB Atlas"
bi-atlas-short = "BI Connector for Atlas"
bi-atlas-short-link = ":doc:`BI Connector for Atlas </atlas-bi-connector>`"
odbc-driver-name = "MongoDB ODBC driver"
tls-ssl = ":abbr:`TLS (Transport Layer Security)`/:abbr:`SSL (Secure Sockets Layer)`"
ssl = ":abbr:`SSL (Secure Sockets Layer)`"
tls = ":abbr:`TLS (Transport Layer Security)`"
http = ":abbr:`HTTP (HyperText Transport Protocol)`"
https = ":abbr:`HTTPS (Secure HyperText Transport Protocol)`"
cidr = ":abbr:`CIDR (Classless Inter-Domain Routing)`"
ipaddr = ":abbr:`IP (Internet Protocol)`"
jira = "`Jira <https://jira.mongodb.org>`__"
epoch-time = "Timestamp in the number of seconds that have elapsed since the `UNIX epoch <https://en.wikipedia.org/wiki/Unix_time?oldid=828172017>`__"
iso8601-time = "Timestamp in `ISO 8601 <https://en.wikipedia.org/wiki/ISO_8601?oldid=793821205>`__ date and time format in |UTC|"
utc = ":abbr:`UTC (Coordinated Universal Time)`"
ldap = ":abbr:`LDAP (Lightweight Directory Access Protocol)`"
ldaps = ":abbr:`LDAPS (Secure Lightweight Directory Access Protocol)`"
kmip = ":abbr:`KMIP (Key Management Interoperability Protocol)`"
url = ":abbr:`URL (Uniform Resource Locator)`"
dsn = ":abbr:`DSN (Data Source Name)`"
odbc = ":abbr:`ODBC (Open Database Connectivity)`"
jdbc = ":abbr:`JDBC (Java Database Connectivity)`"
sql = ":abbr:`SQL (Structured Query Language)`"
kdc = ":abbr:`KDC (Key Distribution Center)`"
adc = ":abbr:`ADC (Active Directory Controller)`"
spn = ":abbr:`SPN (Service Principal Name)`"
upn = ":abbr:`UPN (User Principal Name)`"
sasl = ":abbr:`SASL (Simple Authentication and Security Layer)`"
iana = ":abbr:`IANA (Internet Assigned Numbers Authority)`"
scram = ":abbr:`SCRAM (Salted Challenge Response Authentication Mechanism)`"

[constants]
bi-atlas-short = "BI Connector for Atlas"
bi-short = "BI Connector"
download-center = "`MongoDB Download Center <https://www.mongodb.com/download-center/bi-connector>`__"
download-center-bi = "`MongoDB Connector for BI <https://www.mongodb.com/download-center/bi-connector>`__"
download-center-tableau = "`MongoDB Connector for BI <https://www.mongodb.com/download-center/bi-connector?jmp=tbl>`__"
download-center-url = "https://www.mongodb.com/download-center/bi-connector"
odbc-driver = "`MongoDB ODBC Driver for BI Connector <https://github.com/mongodb/mongo-odbc-driver/releases/>`__"
